# Generated by Django 4.2.4 on 2023-08-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeesId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeesName', models.CharField(max_length=90)),
                ('Department', models.CharField(max_length=90)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=90)),
            ],
        ),
    ]
